### ISSUE TITLE
Incorrect datetime value: 'NOW()' for column 'lasted' 

### ISSUE THREAD

**Issue by jools-r** [Bloke/smd_babel#1]
With txp 4.9, php 8.3 and MySQL 8.3, I'm getting the following error in the XHR returned after adding a new term, and the new term is not added:

```
Incorrect datetime value: 'NOW()' for column 'lastmod' 
```

for the lines https://github.com/Bloke/smd_babel/blob/d42e6aa84cfe13ffd8903ffed6071886209a9553/smd_babel.php#L521 and https://github.com/Bloke/smd_babel/blob/d42e6aa84cfe13ffd8903ffed6071886209a9553/smd_babel.php#L630

Is there a trick needed to insert `NOW()` into a DateTime field in more recent MySQL versions?

For the moment I resolved it by inserting the current datestamp via PHP `'lastmod' => date("Y-m-d H:i:s"),` for each instance, but you likely have a better way.

_EDIT: lasted -> lastmod. Autocorrect strikes back_

**Comment by Bloke** [comment]
I'm curious why `NOW()` wouldn't work. As far as I know it's not deprecated. Weird. Might be that the definition of the column itself needs changing. Hmmm.
